import { 
  RedditIconOfficial, 
  GitHubIconOfficial, 
  GmailIconOfficial, 
  CalendarIconOfficial, 
  NotionIconOfficial, 
  SlackIconOfficial, 
  DiscordIconOfficial,
  OutlookIconOfficial,
  AsanaIconOfficial,
  TrelloIconOfficial,
  LinearIconOfficial,
  ClickUpIconOfficial,
  VercelIconOfficial,
  NetlifyIconOfficial,
  SupabaseIconOfficial,
  SentryIconOfficial,
  PostHogIconOfficial,
  WebflowIconOfficial,
  DevinIconOfficial,
  CursorIconOfficial,
  CanvaIconOfficial,
  GranolaIconOfficial,
  DropboxIconOfficial,
  XIconOfficial,
  StravaIconOfficial,
  FitbitIconOfficial,
  OuraIconOfficial,
  WithingsIconOfficial,
  MercuryIconOfficial,
  RampIconOfficial,
  NavanIconOfficial
} from '../components/common/icons/PlatformIcons';

export const ALL_POSSIBLE_PLATFORMS = [
  { id: 'github', name: 'GitHub', icon: <GitHubIconOfficial />, description: 'Sync repositories, pull requests, and code history.' },
  { id: 'gmail', name: 'Gmail', icon: <GmailIconOfficial />, description: 'Index your entire email history and communications.' },
  { id: 'google-calendar', name: 'Google Calendar', icon: <CalendarIconOfficial />, description: 'Track your meetings, events, and time allocation.' },
  { id: 'outlook', name: 'Outlook', icon: <OutlookIconOfficial />, description: 'Connect Microsoft 365 mail and calendar data.' },
  { id: 'reddit', name: 'Reddit', icon: <RedditIconOfficial />, description: 'Analyze your comments, posts, and saved history.' },
  { id: 'notion', name: 'Notion', icon: <NotionIconOfficial />, description: 'Search through your pages, databases, and workspace.' },
  { id: 'slack', name: 'Slack', icon: <SlackIconOfficial />, description: 'Index channel messages and direct communications.' },
  { id: 'discord', name: 'Discord', icon: <DiscordIconOfficial />, description: 'Connect servers and private messaging history.' },
  { id: 'twitter', name: 'Twitter (X)', icon: <XIconOfficial />, description: 'Sync your tweets, mentions, and social footprint.' },
  { id: 'dropbox', name: 'Dropbox', icon: <DropboxIconOfficial />, description: 'Search and index your cloud files and metadata.' },
  { id: 'asana', name: 'Asana', icon: <AsanaIconOfficial />, description: 'Track project tasks, goals, and team progress.' },
  { id: 'trello', name: 'Trello', icon: <TrelloIconOfficial />, description: 'Index boards, cards, and workflow history.' },
  { id: 'linear', name: 'Linear', icon: <LinearIconOfficial />, description: 'Sync engineering tickets, cycles, and roadmaps.' },
  { id: 'clickup', name: 'ClickUp', icon: <ClickUpIconOfficial />, description: 'Connect your all-in-one productivity workspace.' },
  { id: 'vercel', name: 'Vercel', icon: <VercelIconOfficial />, description: 'Track deployments, logs, and project health.' },
  { id: 'netlify', name: 'Netlify', icon: <NetlifyIconOfficial />, description: 'Index site builds and deployment history.' },
  { id: 'supabase', name: 'Supabase', icon: <SupabaseIconOfficial />, description: 'Connect database logs and infrastructure context.' },
  { id: 'sentry', name: 'Sentry', icon: <SentryIconOfficial />, description: 'Monitor error logs and application health.' },
  { id: 'posthog', name: 'PostHog', icon: <PostHogIconOfficial />, description: 'Analyze product usage and event analytics.' },
  { id: 'webflow', name: 'Webflow', icon: <WebflowIconOfficial />, description: 'Index site designs and publishing history.' },
  { id: 'devin', name: 'Devin', icon: <DevinIconOfficial />, description: 'Sync autonomous engineering agent task history.' },
  { id: 'cursor', name: 'Cursor', icon: <CursorIconOfficial />, description: 'Track AI-assisted coding sessions and history.' },
  { id: 'canva', name: 'Canva', icon: <CanvaIconOfficial />, description: 'Index design projects and brand assets.' },
  { id: 'granola', name: 'Granola', icon: <GranolaIconOfficial />, description: 'Sync AI-enhanced meeting notes and context.' },
  { id: 'strava', name: 'Strava', icon: <StravaIconOfficial />, description: 'Connect athletic activities and fitness data.' },
  { id: 'fitbit', name: 'Fitbit', icon: <FitbitIconOfficial />, description: 'Track steps, sleep, and biometric trends.' },
  { id: 'oura', name: 'Oura', icon: <OuraIconOfficial />, description: 'Sync sleep cycles, readiness, and ring data.' },
  { id: 'withings', name: 'Withings', icon: <WithingsIconOfficial />, description: 'Monitor weight, blood pressure, and health trends.' },
  { id: 'mercury', name: 'Mercury', icon: <MercuryIconOfficial />, description: 'Connect corporate banking and transaction history.' },
  { id: 'ramp', name: 'Ramp', icon: <RampIconOfficial />, description: 'Sync corporate spend and expense management.' },
  { id: 'navan', name: 'Navan', icon: <NavanIconOfficial />, description: 'Track travel bookings and business expenses.' }
];
