import { 
  GitHubIconOfficial, 
  GmailIconOfficial, 
  CalendarIconOfficial, 
  NotionIconOfficial, 
  SlackIconOfficial, 
  DiscordIconOfficial,
  AsanaIconOfficial,
  TrelloIconOfficial,
  LinearIconOfficial,
  ClickUpIconOfficial,
  VercelIconOfficial,
  NetlifyIconOfficial,
  SupabaseIconOfficial,
  SentryIconOfficial,
  PostHogIconOfficial,
  WebflowIconOfficial,
  DevinIconOfficial,
  CursorIconOfficial,
  CanvaIconOfficial,
  DropboxIconOfficial,
  XIconOfficial,
  StravaIconOfficial,
  FitbitIconOfficial,
  WithingsIconOfficial,
  RedditIconOfficial
} from '../components/common/icons/PlatformIcons';

export const ALL_POSSIBLE_PLATFORMS = [
  { id: 'github', name: 'GitHub', icon: <GitHubIconOfficial />, category: 'Development', description: 'Sync repositories, pull requests, and code history.', color: 'var(--text-primary)' },
  { id: 'gmail', name: 'Gmail', icon: <GmailIconOfficial />, category: 'Productivity', description: 'Index your entire email history and communications.', color: '#ea4335' },
  { id: 'google-calendar', name: 'Google Calendar', icon: <CalendarIconOfficial />, category: 'Productivity', description: 'Track your meetings, events, and time allocation.', color: '#4285f4' },
  { id: 'notion', name: 'Notion', icon: <NotionIconOfficial />, category: 'Productivity', description: 'Search through your pages, databases, and workspace.', color: 'var(--text-primary)' },
  { id: 'slack', name: 'Slack', icon: <SlackIconOfficial />, category: 'Productivity', description: 'Index channel messages and direct communications.', color: '#e01e5a' },
  { id: 'discord', name: 'Discord', icon: <DiscordIconOfficial />, category: 'Social', description: 'Connect servers and private messaging history.', color: '#5865f2' },
  { id: 'twitter', name: 'Twitter (X)', icon: <XIconOfficial />, category: 'Social', description: 'Sync your tweets, mentions, and social footprint.', color: 'var(--text-primary)' },
  { id: 'reddit', name: 'Reddit', icon: <RedditIconOfficial />, category: 'Social', description: 'Index your subreddits, comments, and posts.', color: '#FF4500' },
  { id: 'dropbox', name: 'Dropbox', icon: <DropboxIconOfficial />, category: 'Productivity', description: 'Search and index your cloud files and metadata.', color: '#0061ff' },
  { id: 'asana', name: 'Asana', icon: <AsanaIconOfficial />, category: 'Productivity', description: 'Track project tasks, goals, and team progress.', color: '#F95D5C' },
  { id: 'trello', name: 'Trello', icon: <TrelloIconOfficial />, category: 'Productivity', description: 'Index boards, cards, and workflow history.', color: '#0079BF' },
  { id: 'linear', name: 'Linear', icon: <LinearIconOfficial />, category: 'Productivity', description: 'Sync engineering tickets, cycles, and roadmaps.', color: '#5E6AD2' },
  { id: 'clickup', name: 'ClickUp', icon: <ClickUpIconOfficial />, category: 'Productivity', description: 'Connect your all-in-one productivity workspace.', color: '#7B68EE' },
  { id: 'vercel', name: 'Vercel', icon: <VercelIconOfficial />, category: 'Development', description: 'Track deployments, logs, and project health.', color: 'var(--text-primary)' },
  { id: 'sentry', name: 'Sentry', icon: <SentryIconOfficial />, category: 'Development', description: 'Monitor error logs and application health.', color: '#362D59' }
];

